### ISSUE TITLE
Bug: tab-indented mis-selection

### ISSUE THREAD

**Issue by amerlyq** [ngn/vim-column#1]
Suppose I have double-tabbed snippet inside vim-outliner:
```
		https://bbs.archlinux.org/viewtopic.php?id=98695
		https://github.com/NickHu/dotxmonad/blob/master/xmonad.hs
		http://wpr.cz/ccx/paste/2012-04-10/1.txt
```
If I stand on first [h] in first line and then press `|` ,  selection will be the next
```
		https:/[/]bbs.archlinux.org/viewtopic.php?id=98695
		https:/[/]github.com/NickHu/dotxmonad/blob/master/xmonad.hs
		http://[w]pr.cz/ccx/paste/2012-04-10/1.txt
```
Which seems like consequence of inequality of character positions with virtualcol.

Moreover, another related problem will arise for wide characters -- like japanese.

**Comment by amerlyq** [comment]
`strdisplaywidth` and `[ \t\u3000]` can be of some help.

**Comment by ngn** [comment]
Thanks!  `strdisplaywidth()` looks quite useful but actually I needed its inverse -- given a virtual column, find out what column number I should pass to `setpos()`.  I ended up using `\%123v` in a regex to compute that. It seems to work even for those wide Japanese characters.
