### ISSUE TITLE
Bug: wide-char problems

### ISSUE THREAD

**Issue by amerlyq** [ngn/vim-column#3]
Test snippet -- each second line indented by two spaces:
```
愛という言葉が　         
  憂いによく似てるって   
僕が気づいたとき         
  夜があけた             
青が争うほどの　         
  静けさに満ちてた       
僕の右側に               
  君は滑り込んできた     
```
There two problems:
* on `|` two adjacent columns selected instead of one (same for operator mode), same with cyrrilic, and I suppose with any other unicode `>= 0x256`
* wide characters are different, but column is selected anyway -- maybe same troubles will arise with any upper unicode?

**Comment by ngn** [comment]
Oops, sorry... off by one.  Fix coming up in a moment.

**Comment by ngn** [comment]
Unfortunately there is still an oddity with "wide" chars, which I don't understand.

**Comment by amerlyq** [comment]
Good, now it seems to work as expected. Thanks for fix:)
